services:
  discord-bot:
    build:
      context: .
      dockerfile: gameBot/Dockerfile
    container_name: discord-liar-bot
    restart: always
    env_file: .env

  music-bot:
    build: ./musicBot
    container_name: discord-music-bot
    restart: always
    env_file: .env
