services:
  discord-bot:
    build: .
    container_name: discord-liar-bot
    restart: always
    env_file: .env

  music-bot:
    build: ./musicBot
    container_name: discord-music-bot
    restart: always
    env_file: .env
